name: ASP.NET CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    env:
      # Load the environment variables from the env.list file
      PATH: ${{ secrets.PATH_CONTENTS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet Packages
      working-directory: src
      run: nuget restore TestWebappforSonar.sln

    - name: Build with MSBuild
      working-directory: src
      run: msbuild TestWebappforSonar.sln /p:Configuration=Release

    # Add more steps for testing or deploying as needed





