name: ASP.NET CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    env:
      # Load the environment variables from the env.list file
      PATH: ${{ secrets.PATH_CONTENTS }}

    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet Packages
      working-directory: src
      run: nuget restore TestWebappforSonar.sln

    - name: Debugging
      run: |
        echo "Before MSBuild"
        msbuild TestWebappforSonar.sln /p:Configuration=Release
        echo "After MSBuild"

    # Add more steps for testing or deploying as needed
